accounts/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path, reverse
from django.shortcuts import redirect
from .views import loginpage, logout_view



def check_user(request):
    user = request.get.user
    if user.is_authenticated:
        if user.is_manager:
            return redirect(reverse('product_App:manager_dashboard'))
        elif user.is_counter_staff():
            return redirect(reverse('product_App:counter_dashboard'))
    return redirect('login/')




app_name = 'accounts'

urlpatterns = [

    path('login/', loginpage, name='login'),
    path('logout/', logout_view, name='logout'),
    path('change-password/check_user/',check_user, name='check_user'),
    path('change-password/', PasswordChangeView.as_view(template_name='change_password.html', success_url = 'check_user/'
        ), name='change_password'),
]

company_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('product_app.urls')),
]



handler404 = 'accounts.views.handle404'

product_app/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views
from django.shortcuts import render



app_name = 'product_app'

urlpatterns = [
    path('manager/manage_staff/history/', views.staff_history_page, name= "manage_staff_history"),
    path('manager/manage_staff/history/loader/<start_date>/<end_date>/<int:staff_id>/', views.staff_history_page_lazy, name="staff_report_loader"),

    path('manager/manage_staff/history/report/', views.get_orders_based_on_date_and_staff_func, name="manage_staff_transactions"),

    path('manager/manage_staff/', views.staff_creation_page, name="manage_staff"),
    path('manager/manage_staff/suspend/<int:staff_id>/', views.suspend, name="suspend_staff"),
    path('manager/manage_staff/pardon/<int:staff_id>/', views.pardon, name="pardon_staff"),

    path('manager/manage_product/', views.product_management_page, name="manage_product"),
    path('manager/manage_product/create_product/', views.create_product, name="create_product"),

    path('manager/manage_product/edit_product_page/<int:product_id>/', views.product_edit_page, name="edit_product"),

    path('manager/manage_product/edit_sub_product_page/<int:sub_product_id>/', views.sub_product_edit_page,
         name="edit_sub_product"),

    path('manager/manage_product/create_sub_product_page/<int:product_id>/', views.create_sub_product,
         name="create_sub_product"),

    path('manager/manage_customer/', views.customer_management_page, name="manage_customer"),
    path('manager/', views.get_orders_based_on_date_func, name="manage_transactions"),
    # path('manager/manage_transactions/search', views.get_orders_based_on_date, name="submit_search"),
    path('manager/manage_transactions/print_report/<start_date>/<end_date>/', views.print_report, name="print_report"),
    path('manager/manage_transactions/print_customer_report/<int:customer_id>/', views.print_customer_report,
         name="print_customer_report"),

    path('counter_staff/', views.counter_dashboard, name="counter_dashboard"),
    path('counter_staff/manage_debtors-balances/', views.manage_debtors, name="manage_debtors"),
    path('counter_staff/manage_debtors-balances/pay_debt/<int:order_id>/', views.pay_debt,
         name="pay_debt"),
    path('counter_staff/create_customers/', views.create_customers, name="create_customers"),
    path('counter_staff/', views.counter_dashboard, name="counter_dashboard"),
    path('counter_staff/create_sub_order/<int:order_id>/', views.create_suborder, name="create_sub_order"),
    path('counter_staff/delete_sub_order/<int:sub_order_id>/', views.delete_suborder, name="delete_sub_order"),
    path('counter_staff/complete_order/<int:order_id>', views.complete_order, name="complete_order"),
    path('counter_staff/complete_order/print_receipt/<int:order_id>', views.print_order_receipt,
         name="print_order_receipt"),

    path('staff/create-staff', views.staff_creation, name='create_staff'),
    path('staff/create_new_staff', views.new_staff_creation, name='staff_creation'),
    path('staff/all_staff', views.staff_lazy_page, name='staff_lazy_loader'),

    path('staff/<int:user_id>/fire-staff', views.staff_deletion, name='delete_staff'),

]

product_app/forms.py
from django import forms
from django.forms import ModelForm, Select

from accounts.models import CustomUser
from .models import Order, Product, ProductSubType, Customer, SubOrder


class UserForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ["email", 'is_counter_staff', 'is_manager', 'password']


class OrderQueryForm(forms.Form):
    start_date = forms.DateTimeField(widget=forms.SelectDateWidget(), label="from")
    end_date = forms.DateTimeField(widget=forms.SelectDateWidget(), label="to")


class OrderQueryStaffForm(forms.Form):
    staff = forms.ModelChoiceField(queryset=CustomUser.objects.filter(is_counter_staff = True),  label="staff name")
    start_date = forms.DateTimeField(widget=forms.SelectDateWidget(), label="from")
    end_date = forms.DateTimeField(widget=forms.SelectDateWidget(), label="to")

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('customer',)


class OrderEditForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('job_name', 'deposit', 'discount',)


class SubOrderForm(forms.ModelForm):
    class Meta:
        model = SubOrder
        fields = ('product_ordered', 'length', 'breadth', 'quantity',)
        widgets = {
            'product_ordered': Select(attrs={'required':True}),
        }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('product_name',)


class ProductSubTypeForm(forms.ModelForm):
    class Meta:
        model = ProductSubType
        fields = ('sub_type_name', "price")


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        exclude = ('created_by', 'date_created')

product_app/views.py
from datetime import datetime, timedelta

from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.template.defaulttags import register
from django.urls import reverse
from django.utils.dateparse import parse_datetime

from accounts.models import CustomUser, Profile
from decorators import manager_required, counter_staff_required
from .forms import OrderQueryForm, OrderForm, OrderEditForm, OrderQueryStaffForm
from .forms import UserForm, ProductForm, ProductSubTypeForm, CustomerForm, SubOrderForm
from .models import Product, ProductSubType, Customer, Order, SubOrder, get_product_details_based_on_date_and_staff
from .models import get_product_details_based_on_date, get_orders_based_on_date, get_orders_based_on_date_and_staff
from .pdfs import render_pdf_view
from .tests import affirm_order_balance


@register.filter
def get_value(dictionary, key):
    return dictionary.get(key)


@register.filter
def analyze_nested_list(the_list, num='0'):
    final_list = []
    for a, b in zip(the_list[0], the_list[1]):
        final_list.append("{} pieces at NGN{}".format(str(b), str(a)))

    return final_list


@register.filter
def get_value_and_relation(dictionary, key):
    s = dictionary.get(key)
    b = s.product
    return b


@manager_required()
def print_report(request, start_date, end_date):
    orders = get_orders_based_on_date(parse_datetime(start_date), parse_datetime(end_date))
    sub_products_details = get_product_details_based_on_date(parse_datetime(start_date), parse_datetime(end_date))
    products = Product.objects.all()
    context = {'orders': orders, 'products': products,
               'sub_products_details': sub_products_details, 'date': datetime.now()}
    return render_pdf_view(request, 'manager_components/manager_report.html', context,
                           "{}--{}-report".format(parse_datetime(start_date), parse_datetime(end_date)))


@manager_required()
def print_customer_report(request, customer_id):
    customer = Customer.objects.get(id=customer_id)
    orders = Order.objects.filter(customer=customer, order_completed = True).order_by("date_created")
    c_total_order_price = 0
    total_discount = 0
    total_funds_received = 0
    total_outstanding_funds = 0
    for order in orders:
        c_total_order_price += order.total_order_price
        total_funds_received += order.deposit
        total_discount += order.discount
        total_outstanding_funds += order.balance
    assert total_outstanding_funds + total_funds_received + total_discount == c_total_order_price
    outstanding_orders = orders.filter(paid_fully=False)
    printed_date = datetime.now()
    context = {'orders': orders, 'outstanding_orders': outstanding_orders,
               'printed_date': printed_date, 'customer': customer,
               'c_total_order_price': c_total_order_price,
               'total_discount': total_discount,
               'total_funds_received': total_funds_received,
               'total_outstanding_funds': total_outstanding_funds,
               }
    return render_pdf_view(request, 'manager_components/manager_customer_report.html', context,
                           "{}-report".format(customer))


@counter_staff_required()
def pay_debt(request, order_id):
    order = Order.objects.get(id=order_id)
    order.deposit = order.balance + order.deposit
    order.balance = 0
    order.paid_fully = True
    order.save()
    return redirect(reverse("product_app:manage_debtors"))


@counter_staff_required()
def create_suborder(request, order_id):
    order = Order.objects.get(id=order_id)
    form = SubOrderForm(request.POST or None)
    if form.is_valid():
        a = form.save(commit=False)
        a.order = order
        a.save()
        return render(request, 'counter_components/subtable.html', {'form': form, 'order': order})
    else:
        return render(request, 'counter_components/sub_order_form.html', {'form': form, 'order': order})


@counter_staff_required()
def delete_suborder(request, sub_order_id):
    sub_order = SubOrder.objects.get(id=sub_order_id)
    order = sub_order.order
    sub_order.delete()
    return render(request, 'counter_components/subtable.html', {'order': order})


@manager_required()
def manager_dashboard(request):
    return render(request, 'manager_base.html', {})


@manager_required()
def staff_creation_page(request):
    all_staff = CustomUser.objects.all()
    return render(request, 'manager_components/staff_manager.html', {'all_staff': all_staff})


@manager_required()
def product_management_page(request):
    products = Product.objects.all()
    products = [product.get_product_details() for product in products]

    return render(request, 'product_page.html', {"products": products})


@manager_required()
def customer_management_page(request):
    customers = Customer.objects.all()

    return render(request, 'customer_page.html', {"customers": customers})


@manager_required()
def get_orders_based_on_date_func(request):
    form = OrderQueryForm(request.POST or None)
    if form.is_valid():
        start_date = form.cleaned_data['start_date']
        end_date = form.cleaned_data['end_date']
        # orders = Order.objects.filter(date_created__range=[start_date, end_date]).filter(order_completed=True)
        orders = get_orders_based_on_date(start_date, end_date)
        sub_products_details = get_product_details_based_on_date(start_date, end_date)
        products = Product.objects.all()
        return render(request, 'transaction_page.html', {'orders': orders,
                                                         'products': products,
                                                         'sub_products_details': sub_products_details})
    return render(request, 'transactions_page.html', {'form': form})

    # Sample.objects.filter(date__range=["2011-01-01", "2011-01-31"])

def staff_history_page(request):
    form = OrderQueryStaffForm(request.POST or None)
    return render(request, 'manager_components/staff_report.html', {'form': form})


@manager_required()
def get_orders_based_on_date_and_staff_func(request):
    form = OrderQueryStaffForm(request.POST or None)
    if form.is_valid():
        start_date = form.cleaned_data['start_date']
        end_date = form.cleaned_data['end_date']
        staff = form.cleaned_data['staff']
        # orders = Order.objects.filter(date_created__range=[start_date, end_date]).filter(order_completed=True)
        orders = get_orders_based_on_date_and_staff(start_date, end_date, staff.id)
        sub_products_details = get_product_details_based_on_date_and_staff(start_date, end_date, staff.id)
        products = Product.objects.all()
        return render(request, 'manager_components/staff_report_page.html', {'orders': orders,
                                                                             'staff': staff,
                                                         'products': products,
                                                         'sub_products_details': sub_products_details})
    return render(request, 'manager_components/staff_report.html', {'form': form})




def staff_history_page_lazy(request, start_date, end_date,  staff_id):
    staff = CustomUser.objects.get(id=staff_id)
    orders = Order.objects.filter(date_created__range=[parse_datetime(start_date),parse_datetime(end_date) + timedelta(days=1)]).filter(
        order_completed=True, counter_staff=staff)
    return render(request, 'manager_components/staff_report_lazy_loader.html', {'orders': orders,
                                                                         'staff': staff,
                                                                        })




@manager_required()
def suspend(request, staff_id):
    staff = CustomUser.objects.get(id=staff_id)
    staff.is_suspended = True
    staff.save()
    return redirect(reverse('product_app:staff_lazy_loader'))


@manager_required()
def pardon(request, staff_id):
    staff = CustomUser.objects.get(id=staff_id)
    staff.is_suspended = False
    staff.save()
    return redirect(reverse('product_app:staff_lazy_loader'))


@manager_required()
def staff_lazy_page(request):
    all_staff = CustomUser.objects.all().exclude(is_superuser=True)
    return render(request, 'manager_components/staff_lazy_loader.html', {'all_staff': all_staff})


@manager_required()
def new_staff_creation(request):
    form1 = UserForm(request.POST or None)
    if form1.is_valid():
        form1.save()

    return render(request, 'manager_components/staff_creation.html', {'form1': form1})


@manager_required()
def product_edit_page(request, product_id):
    product = Product.objects.get(id=product_id)
    form = ProductForm(request.POST or None, instance=product)
    if form.is_valid():
        form.save()
        return redirect(reverse('product_app:manage_product'))
    else:
        return render(request, 'manager_components/product_edit_page.html', {'form': form, 'product': product})


@manager_required()
def create_product(request):
    form = ProductForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect(reverse('product_app:manage_product'))
    else:
        return render(request, 'manager_components/create_product.html', {'form': form})


@manager_required()
def sub_product_edit_page(request, sub_product_id):
    sub_product = ProductSubType.objects.get(id=sub_product_id)
    form = ProductSubTypeForm(request.POST or None, instance=sub_product)
    if form.is_valid():
        form.save()
        return redirect(reverse('product_app:manage_product'))
    else:
        return render(request, 'manager_components/sub_product_edit_page.html',
                      {'form': form, 'sub_product': sub_product})


@manager_required()
def create_sub_product(request, product_id):
    product = Product.objects.get(id=product_id)
    form = ProductSubTypeForm(request.POST or None)

product_app/templates/create_customer.html
{%extends 'counter_staff_base.html'%}

{%block content%}

<turbo-frame id="create_order">
    <style>
input[type=text],input[type=number], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #10233b;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #214e8a;
}
.form_frame {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;


    </style>


    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="{{ message.tags }}" style="background-color:green;color:white">
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="form_frame">


        <form action="{%url 'product_app:create_customers'%}" method="post">
            {%csrf_token%}
            {{form.as_p}}

            <input type="submit">
        </form>
    </div>


</turbo-frame>
{%endblock%}

product_app/templates/create_order.html
{%extends 'counter_staff_base.html'%}

{%block content%}


<style>
input[type=text],input[type=number], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #10233b;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #214e8a;
}
.form_frame {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;

</style>

<div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-lg rounded">
    <div class="rounded-t mb-0 px-4 py-3 border-0 form_frame">


        <turbo-frame id="create_order">
            <style>
input[type=text],input[type=number], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #10233b;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #214e8a;
}
.form_frame {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;

            </style>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li class="{{ message.tags }}" style="background-color:green;color:white">
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            {% if order %}
            <p style="background-color:green;color:white">Your order was successful, print the receipt <a
                    href="{%url 'product_app:print_order_receipt' order.id%}" style="color:blue"
                    target="_blank">here</a></p>
            {% endif %}

            <form action="{%url 'product_app:counter_dashboard'%}" method="post">

                {%csrf_token%}
                {{form.as_p}}
                <input type="submit">

            </form>
        </turbo-frame>
    </div>
</div>


{%endblock%}

product_app/templates/customer_page.html
{% extends 'manager_base.html' %}
{% block content %}


<div class="flex flex-col">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">

                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                    <tr>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                            scope="col">
                            Name
                        </th>

                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                            scope="col">
                            Phone Number
                        </th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                            scope="col">
                            Date Joined
                        </th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                            scope="col">
                            Address
                        </th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                            scope="col">
                            Creator
                        </th>
                        <th class="relative px-6 py-3" scope="col">
                            <span class="sr-only">Edit</span>
                        </th>
                    </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                    {%for customer in customers%}
                    <tr>

                        <td class="px-6 py-4 whitespace-nowrap">
                            <div class="flex items-center">

                                <div class="ml-4">
                                    <div class="text-sm font-medium text-gray-900">
                                        {{customer}}
                                    </div>

                                </div>
                            </div>
                        </td>

                        <td class="px-6 py-4 whitespace-nowrap">
                            {{customer.phone_number}}

                        </td>

                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                            {{customer.date_created}}
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                            {{customer.address}}
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                            {{customer.created_by.profile}}
                        </td>

                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                            <a class="text-blue-500" href="{%url 'product_app:print_customer_report' customer.id%}">print
                                transaction history</a>
                        </td>

                    </tr>
                    {%endfor%}
                    <!-- More people... -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}


class customer(models.Model):
created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True)
company_name = models.CharField(max_length=300)
customer_last_name = models.CharField(max_length=300, null=True, blank=True)
phone_number = models.CharField(max_length=11, unique=True)
date_created = models.DateTimeField(auto_now=True)

def __str__(self):
return '{} {}'.format(self.company_name, self.customer_last_name)

def get_details(self):
details = {"full_name": "{} {}".format(self.company_name.capitalize(), self.customer_last_name.capitalize()),
"phone_number": self.phone_number,
"created_by": self.created_by,
"date_created": self.date_created,

"transaction_history": self.get_transaction_history(),
}
return details

def get_transaction_history(self):
details = {
"all_orders": Order.objects.filter(customer=self).order_by("date_created"),
'outstanding_orders' : Order.objects.filter(customer=self, order_completed = True, paid_fully =False).order_by("date_created"),


}
return details

product_app/templates/product_page.html
{% extends 'manager_base.html' %}
{% block content %}

<style>
    @media screen and (max-width : 320px)
{
  .product
  {
    font:15px;
  }
  .time{
  font:15px;
  }
}
@media screen and (max-width : 1204px)
{
  .product
  {
    font:20px;
  }
  .time{
  font:150px;
  }
}

</style>
<turbo-frame id="product_creation">
    <div class="flex flex-wrap items-center">
        <div class="relative w-full px-4 max-w-full flex-grow flex-1 text-left"
             style="padding:20px;margin-bottom:20px; ">
            <a class="bg-indigo-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1"
               href="{%url 'product_app:create_product'%}"
               style="transition:all .15s ease; background-color:#10233b" type="button">
                Create Product
            </a>
        </div>
    </div>

    {%for product in products%}
    <div class="w-full xl:w-8/12 mb-12 xl:mb-0 px-4">

        <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-lg rounded">
            <div class="rounded-t mb-0 px-4 py-3 border-0">


                <turbo-frame id="{{ product|get_value:'product_id' }}-12345">
                    <div class="flex flex-wrap items-center">
                        <div class="relative w-full px-4 max-w-full flex-grow flex-1">
                            <h1 class="font-semibold text-base text-blueGray-900 product">
                                <strong>{{ product|get_value:'product_name' }}</strong>
                            </h1>
                            <h5 class="font-semibold text-base text-blueGray-700 time">
                                Date Created: {{ product|get_value:'date_created' }}
                            </h5>
                        </div>
                        <div class="relative w-full px-4 max-w-full flex-grow flex-1 text-right">
                            <a class="bg-indigo-500 text-white active:bg-indigo-600 text-xs font-bold uppercase px-3 py-1 rounded outline-none focus:outline-none mr-1 mb-1"
                               href="{%url 'product_app:edit_product' product|get_value:'product_id'%}"
                               style="transition:all .15s ease;background-color: #214e8a; color:white; font-size:10px"
                               type="button">
                                Edit Product
                            </a>
                        </div>
                    </div>
                </turbo-frame>
            </div>
            <turbo-frame id="create_subtype-{{ product|get_value:'product_id' }}">
                <div class="block w-full overflow-x-auto">
                    <!-- Projects table -->
                    <table class="items-center w-full bg-transparent border-collapse">
                        <thead>
                        <tr>
                            <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                Sub Product Name
                            </th>
                            <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                Fixed Price
                            </th>
                            <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                Last price change date
                            </th>
                            <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">

                            </th>

                        </tr>
                        </thead>
                        <tbody>
                        {%for sub_product in product|get_value:'product_sub_types'%}

                        <tr>


                            <th class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left">
                                {{sub_product.sub_type_name}}
                            </th>

                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                N {{sub_product.price}}
                            </td>
                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                {{sub_product.last_price_changed_date}}
                            </td>


                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">


                                <a href="{%url 'product_app:edit_sub_product' sub_product.id%}" style="transition:all .15s ease; color:blue"
                                   type="button">
                                    Edit Sub Product
                                </a>
                            </td>


                        </tr>


                        {%endfor%}

                        </tbody>

                    </table>
                </div>
                <a href="{%url 'product_app:create_sub_product' product|get_value:'product_id'%}" style="transition:all .15s ease;background-color: #214e8a; color:white; font-size:10px"
                   type="button">
                    Add Sub Product
                </a>

            </turbo-frame>
        </div>

    </div>


    {%endfor%}
</turbo-frame>
{% endblock %}

product_app/templates/profile.html
{% extends 'manager_base.html' %}

{% block content %}
<h1 style="font-size:100px">Hello profile World</h1>
{% endblock %}