accounts/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path, reverse
from django.shortcuts import redirect
from .views import loginpage, logout_view



def check_user(request):
    user = request.get.user
    if user.is_authenticated:
        if user.is_manager:
            return redirect(reverse('product_App:manager_dashboard'))
        elif user.is_counter_staff():
            return redirect(reverse('product_App:counter_dashboard'))
    return redirect('login/')




app_name = 'accounts'

urlpatterns = [

    path('login/', loginpage, name='login'),
    path('logout/', logout_view, name='logout'),
    path('change-password/check_user/',check_user, name='check_user'),
    path('change-password/', PasswordChangeView.as_view(template_name='change_password.html', success_url = 'check_user/'
        ), name='change_password'),
]

company_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('product_app.urls')),
]



handler404 = 'accounts.views.handle404'

product_app/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views
from django.shortcuts import render



app_name = 'product_app'

urlpatterns = [
    path('manager/manage_staff/history/', views.staff_history_page, name= "manage_staff_history"),
    path('manager/manage_staff/history/loader/<start_date>/<end_date>/<int:staff_id>/', views.staff_history_page_lazy, name="staff_report_loader"),

    path('manager/manage_staff/history/report/', views.get_orders_based_on_date_and_staff_func, name="manage_staff_transactions"),

    path('manager/manage_staff/', views.staff_creation_page, name="manage_staff"),
    path('manager/manage_staff/suspend/<int:staff_id>/', views.suspend, name="suspend_staff"),
    path('manager/manage_staff/pardon/<int:staff_id>/', views.pardon, name="pardon_staff"),

    path('manager/manage_product/', views.product_management_page, name="manage_product"),
    path('manager/manage_product/create_product/', views.create_product, name="create_product"),

    path('manager/manage_product/edit_product_page/<int:product_id>/', views.product_edit_page, name="edit_product"),

    path('manager/manage_product/edit_sub_product_page/<int:sub_product_id>/', views.sub_product_edit_page,
         name="edit_sub_product"),

    path('manager/manage_product/create_sub_product_page/<int:product_id>/', views.create_sub_product,
         name="create_sub_product"),

    path('manager/manage_customer/', views.customer_management_page, name="manage_customer"),
    path('manager/', views.get_orders_based_on_date_func, name="manage_transactions"),
    # path('manager/manage_transactions/search', views.get_orders_based_on_date, name="submit_search"),
    path('manager/manage_transactions/print_report/<start_date>/<end_date>/', views.print_report, name="print_report"),
    path('manager/manage_transactions/print_customer_report/<int:customer_id>/', views.print_customer_report,
         name="print_customer_report"),

    path('counter_staff/', views.counter_dashboard, name="counter_dashboard"),
    path('counter_staff/manage_debtors-balances/', views.manage_debtors, name="manage_debtors"),
    path('counter_staff/manage_debtors-balances/pay_debt/<int:order_id>/', views.pay_debt,
         name="pay_debt"),
    path('counter_staff/create_customers/', views.create_customers, name="create_customers"),
    path('counter_staff/', views.counter_dashboard, name="counter_dashboard"),
    path('counter_staff/create_sub_order/<int:order_id>/', views.create_suborder, name="create_sub_order"),
    path('counter_staff/delete_sub_order/<int:sub_order_id>/', views.delete_suborder, name="delete_sub_order"),
    path('counter_staff/complete_order/<int:order_id>', views.complete_order, name="complete_order"),
    path('counter_staff/complete_order/print_receipt/<int:order_id>', views.print_order_receipt,
         name="print_order_receipt"),

    path('staff/create-staff', views.staff_creation, name='create_staff'),
    path('staff/create_new_staff', views.new_staff_creation, name='staff_creation'),
    path('staff/all_staff', views.staff_lazy_page, name='staff_lazy_loader'),

    path('staff/<int:user_id>/fire-staff', views.staff_deletion, name='delete_staff'),

]

product_app/forms.py
from django import forms
from django.forms import ModelForm, Select

from accounts.models import CustomUser
from .models import Order, Product, ProductSubType, Customer, SubOrder


class UserForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ["email", 'is_counter_staff', 'is_manager', 'password']


class OrderQueryForm(forms.Form):
    start_date = forms.DateTimeField(widget=forms.SelectDateWidget(), label="from")
    end_date = forms.DateTimeField(widget=forms.SelectDateWidget(), label="to")


class OrderQueryStaffForm(forms.Form):
    staff = forms.ModelChoiceField(queryset=CustomUser.objects.filter(is_counter_staff = True),  label="staff name")
    start_date = forms.DateTimeField(widget=forms.SelectDateWidget(), label="from")
    end_date = forms.DateTimeField(widget=forms.SelectDateWidget(), label="to")

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('customer',)


class OrderEditForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('job_name', 'deposit', 'discount',)


class SubOrderForm(forms.ModelForm):
    class Meta:
        model = SubOrder
        fields = ('product_ordered', 'length', 'breadth', 'quantity',)
        widgets = {
            'product_ordered': Select(attrs={'required':True}),
        }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('product_name',)


class ProductSubTypeForm(forms.ModelForm):
    class Meta:
        model = ProductSubType
        fields = ('sub_type_name', "price")


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        exclude = ('created_by', 'date_created')

product_app/views.py
from datetime import datetime, timedelta

from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.template.defaulttags import register
from django.urls import reverse
from django.utils.dateparse import parse_datetime

from accounts.models import CustomUser, Profile
from decorators import manager_required, counter_staff_required
from .forms import OrderQueryForm, OrderForm, OrderEditForm, OrderQueryStaffForm
from .forms import UserForm, ProductForm, ProductSubTypeForm, CustomerForm, SubOrderForm
from .models import Product, ProductSubType, Customer, Order, SubOrder, get_product_details_based_on_date_and_staff
from .models import get_product_details_based_on_date, get_orders_based_on_date, get_orders_based_on_date_and_staff
from .pdfs import render_pdf_view
from .tests import affirm_order_balance


@register.filter
def get_value(dictionary, key):
    return dictionary.get(key)


@register.filter
def analyze_nested_list(the_list, num='0'):
    final_list = []
    for a, b in zip(the_list[0], the_list[1]):
        final_list.append("{} pieces at NGN{}".format(str(b), str(a)))

    return final_list


@register.filter
def get_value_and_relation(dictionary, key):
    s = dictionary.get(key)
    b = s.product
    return b


@manager_required()
def print_report(request, start_date, end_date):
    orders = get_orders_based_on_date(parse_datetime(start_date), parse_datetime(end_date))
    sub_products_details = get_product_details_based_on_date(parse_datetime(start_date), parse_datetime(end_date))
    products = Product.objects.all()
    context = {'orders': orders, 'products': products,
               'sub_products_details': sub_products_details, 'date': datetime.now()}
    return render_pdf_view(request, 'manager_components/manager_report.html', context,
                           "{}--{}-report".format(parse_datetime(start_date), parse_datetime(end_date)))


@manager_required()
def print_customer_report(request, customer_id):
    customer = Customer.objects.get(id=customer_id)
    orders = Order.objects.filter(customer=customer, order_completed = True).order_by("date_created")
    c_total_order_price = 0
    total_discount = 0
    total_funds_received = 0
    total_outstanding_funds = 0
    for order in orders:
        c_total_order_price += order.total_order_price
        total_funds_received += order.deposit
        total_discount += order.discount
        total_outstanding_funds += order.balance
    assert total_outstanding_funds + total_funds_received + total_discount == c_total_order_price
    outstanding_orders = orders.filter(paid_fully=False)
    printed_date = datetime.now()
    context = {'orders': orders, 'outstanding_orders': outstanding_orders,
               'printed_date': printed_date, 'customer': customer,
               'c_total_order_price': c_total_order_price,
               'total_discount': total_discount,
               'total_funds_received': total_funds_received,
               'total_outstanding_funds': total_outstanding_funds,
               }
    return render_pdf_view(request, 'manager_components/manager_customer_report.html', context,
                           "{}-report".format(customer))


@counter_staff_required()
def pay_debt(request, order_id):
    order = Order.objects.get(id=order_id)
    order.deposit = order.balance + order.deposit
    order.balance = 0
    order.paid_fully = True
    order.save()
    return redirect(reverse("product_app:manage_debtors"))


@counter_staff_required()
def create_suborder(request, order_id):
    order = Order.objects.get(id=order_id)
    form = SubOrderForm(request.POST or None)
    if form.is_valid():
        a = form.save(commit=False)
        a.order = order
        a.save()
        return render(request, 'counter_components/subtable.html', {'form': form, 'order': order})
    else:
        return render(request, 'counter_components/sub_order_form.html', {'form': form, 'order': order})


@counter_staff_required()
def delete_suborder(request, sub_order_id):
    sub_order = SubOrder.objects.get(id=sub_order_id)
    order = sub_order.order
    sub_order.delete()
    return render(request, 'counter_components/subtable.html', {'order': order})


@manager_required()
def manager_dashboard(request):
    return render(request, 'manager_base.html', {})


@manager_required()
def staff_creation_page(request):
    all_staff = CustomUser.objects.all()
    return render(request, 'manager_components/staff_manager.html', {'all_staff': all_staff})


@manager_required()
def product_management_page(request):
    products = Product.objects.all()
    products = [product.get_product_details() for product in products]

    return render(request, 'product_page.html', {"products": products})


@manager_required()
def customer_management_page(request):
    customers = Customer.objects.all()

    return render(request, 'customer_page.html', {"customers": customers})


@manager_required()
def get_orders_based_on_date_func(request):
    form = OrderQueryForm(request.POST or None)
    if form.is_valid():
        start_date = form.cleaned_data['start_date']
        end_date = form.cleaned_data['end_date']
        # orders = Order.objects.filter(date_created__range=[start_date, end_date]).filter(order_completed=True)
        orders = get_orders_based_on_date(start_date, end_date)
        sub_products_details = get_product_details_based_on_date(start_date, end_date)
        products = Product.objects.all()
        return render(request, 'transaction_page.html', {'orders': orders,
                                                         'products': products,
                                                         'sub_products_details': sub_products_details})
    return render(request, 'transactions_page.html', {'form': form})

    # Sample.objects.filter(date__range=["2011-01-01", "2011-01-31"])

def staff_history_page(request):
    form = OrderQueryStaffForm(request.POST or None)
    return render(request, 'manager_components/staff_report.html', {'form': form})


@manager_required()
def get_orders_based_on_date_and_staff_func(request):
    form = OrderQueryStaffForm(request.POST or None)
    if form.is_valid():
        start_date = form.cleaned_data['start_date']
        end_date = form.cleaned_data['end_date']
        staff = form.cleaned_data['staff']
        # orders = Order.objects.filter(date_created__range=[start_date, end_date]).filter(order_completed=True)
        orders = get_orders_based_on_date_and_staff(start_date, end_date, staff.id)
        sub_products_details = get_product_details_based_on_date_and_staff(start_date, end_date, staff.id)
        products = Product.objects.all()
        return render(request, 'manager_components/staff_report_page.html', {'orders': orders,
                                                                             'staff': staff,
                                                         'products': products,
                                                         'sub_products_details': sub_products_details})
    return render(request, 'manager_components/staff_report.html', {'form': form})




def staff_history_page_lazy(request, start_date, end_date,  staff_id):
    staff = CustomUser.objects.get(id=staff_id)
    orders = Order.objects.filter(date_created__range=[parse_datetime(start_date),parse_datetime(end_date) + timedelta(days=1)]).filter(
        order_completed=True, counter_staff=staff)
    return render(request, 'manager_components/staff_report_lazy_loader.html', {'orders': orders,
                                                                         'staff': staff,
                                                                        })




@manager_required()
def suspend(request, staff_id):
    staff = CustomUser.objects.get(id=staff_id)
    staff.is_suspended = True
    staff.save()
    return redirect(reverse('product_app:staff_lazy_loader'))


@manager_required()
def pardon(request, staff_id):
    staff = CustomUser.objects.get(id=staff_id)
    staff.is_suspended = False
    staff.save()
    return redirect(reverse('product_app:staff_lazy_loader'))


@manager_required()
def staff_lazy_page(request):
    all_staff = CustomUser.objects.all().exclude(is_superuser=True)
    return render(request, 'manager_components/staff_lazy_loader.html', {'all_staff': all_staff})


@manager_required()
def new_staff_creation(request):
    form1 = UserForm(request.POST or None)
    if form1.is_valid():
        form1.save()

    return render(request, 'manager_components/staff_creation.html', {'form1': form1})


@manager_required()
def product_edit_page(request, product_id):
    product = Product.objects.get(id=product_id)
    form = ProductForm(request.POST or None, instance=product)
    if form.is_valid():
        form.save()
        return redirect(reverse('product_app:manage_product'))
    else:
        return render(request, 'manager_components/product_edit_page.html', {'form': form, 'product': product})


@manager_required()
def create_product(request):
    form = ProductForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect(reverse('product_app:manage_product'))
    else:
        return render(request, 'manager_components/create_product.html', {'form': form})


@manager_required()
def sub_product_edit_page(request, sub_product_id):
    sub_product = ProductSubType.objects.get(id=sub_product_id)
    form = ProductSubTypeForm(request.POST or None, instance=sub_product)
    if form.is_valid():
        form.save()
        return redirect(reverse('product_app:manage_product'))
    else:
        return render(request, 'manager_components/sub_product_edit_page.html',
                      {'form': form, 'sub_product': sub_product})


@manager_required()
def create_sub_product(request, product_id):
    product = Product.objects.get(id=product_id)
    form = ProductSubTypeForm(request.POST or None)

product_app/templates/manager_components/create_product.html
<turbo-frame id="product_creation">

    <style>
input[type=text],input[type=number], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 100%;
  background-color: #10233b;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #214e8a;
}
.form_frame {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;

    </style>
    <div class="form_frame">
        <form action="{%url 'product_app:create_product'%}" method="post">
            {%csrf_token%}
            {{form.as_p}}
            <input type="submit"> <input type="button">
        </form>
    </div>


</turbo-frame>

product_app/templates/manager_components/staff_lazy_loader.html
<turbo-frame id="staff_lazy_loader">
    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li class="{{ message.tags }}" style="background-color:red;color:white">
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider" scope="col">
                    Name
                </th>

                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider" scope="col">
                    Status
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider" scope="col">
                    Role
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider" scope="col">
                    Address
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider" scope="col">
                    Phone Number
                </th>
                <th class="relative px-6 py-3" scope="col">
                    <span class="sr-only">Edit</span>
                </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            {%for staff in all_staff%}
            <tr>

                <td class="px-6 py-4 whitespace-nowrap">
                    <div class="flex items-center">

                        <div class="ml-4">
                            <div class="text-sm font-medium text-gray-900">
                                {{staff.profile}}
                            </div>
                            <div class="text-sm text-gray-500">
                                {{staff.email}}
                            </div>
                        </div>
                    </div>
                </td>

                <td class="px-6 py-4 whitespace-nowrap">
                    {%if staff.is_suspended%}
                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-red-800"
                          style="background-color:red; color:white;">
                    Suspended
                </span>
                    {%else%}
                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800"
                          style="background-color:green; color:white;">
                    Active
                </span>
                    {%endif%}
                </td>

                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {%if staff.is_manager%}Manager{%elif staff.is_counter_staff%}Counter Staff{%elif staff.is_director%}Director{%endif%}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{staff.profile.address}}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{staff.profile.phone_number}}
                </td>
                {%if not staff.email == request.user.email and not staff.is_director %}
                {%if staff.is_suspended%}
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                    <a class="text-indigo-600 hover:text-indigo-900" href="{%url 'product_app:pardon_staff' staff.id%}">pardon</a>
                </td>
                {%else%}
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                    <a class="text-indigo-600 hover:text-indigo-900"
                       href="{%url 'product_app:suspend_staff' staff.id%}">suspend</a>
                </td>
                {%endif%}
                {%endif%}



            </tr>
            {%endfor%}

            <!-- More people... -->
            </tbody>
        </table>


    </div>

    <br>
    <a class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" href="{%url 'product_app:staff_creation'%}"
       style="margin:50px;background-color:#10233b; font-size:1.8vw;">
        Create Staff
    </a>


</turbo-frame>

product_app/templates/manager_components/staff_manager.html
{% extends 'manager_base.html' %}

{% block content %}
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="flex flex-col">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
            <turbo-frame id="staff_lazy_loader" src="{%url 'product_app:staff_lazy_loader'%}">
                <h1>LOADING</h1>
            </turbo-frame>

        </div>

    </div>

</div>


{% endblock %}

product_app/templates/manager_components/staff_report_page.html
{% extends 'manager_base.html' %}
{% block content %}
<style>
input[type=text],input[type=number], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

.button {
  width: 100%;
  background-color: #10233b;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #214e8a;
}
.form_frame {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;

</style>

<div class="w-full xl:w-8/12 mb-12 xl:mb-0 px-4">
    <turbo-frame id="hi">

        <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-lg rounded">
            <div class="rounded-t mb-0 px-4 py-3 border-0">
                <a class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow"
                   href="{%url 'product_app:manage_staff_history'%}">Change date range</a>
            </div>
            <div class="relative w-full px-4 max-w-full flex-grow flex-1">
                 <h1 class="font-semibold text-base text-blueGray-900">
                    staff: {{ staff }}
                </h1>
                <h1 class="font-semibold text-base text-blueGray-900">
                    from: {{ orders|get_value:'start_date' }}
                </h1>
                <h5 class="font-semibold text-base text-blueGray-700">
                    to: {{ orders|get_value:'end_date' }}
                </h5>
            </div>

        </div>


        <div class="flex flex-col">
            {%for product in products%}
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">


                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <h1 class="font-semibold bg-white text-base text-blueGray-900">
                            {{ product.product_name }}
                        </h1>
                        <table class="min-w-full divide-y divide-gray-200">
                            <thead class="bg-gray-50">
                            <tr>
                                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                    scope="col">
                                    SubProductName
                                </th>

                                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                    scope="col">
                                    Total Piece Ordered
                                </th>
                                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                    scope="col">
                                    Total Expected Income
                                </th>
                                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                                    scope="col">
                                    Price/quantity sold
                                </th>

                            </tr>
                            </thead>
                            <tbody class="bg-white divide-y divide-gray-200">
                            {%for each_sub_product in sub_products_details%}
                            {%with sub_product=each_sub_product|get_value:'sub_product'%}
                            {%if sub_product.product == product%}
                            <tr>

                                <th class="px-6 py-4 whitespace-nowrap">
                                    <div class="flex items-center">

                                        <div class="ml-4">
                                            <div class="text-sm font-medium text-gray-900">
                                                {{each_sub_product|get_value:'sub_product'}}
                                            </div>

                                        </div>
                                    </div>
                                </th>

                                <td class="px-6 py-4 whitespace-nowrap">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                    {{each_sub_product|get_value:'total_piece_ordered'}}
                </span>

                                </td>

                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{each_sub_product|get_value:'total_expected_income'}}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {%with price_list=each_sub_product|get_value:'price_list'%}
                                    {%with final_list=price_list|analyze_nested_list:'0'%}
                                    {%for each in final_list%}
                                    <p>{{each}}</p>
                                    {%endfor%}

                                    {%endwith%}{%endwith%}
                                </td>


                            </tr>
                            {%endif%}
                            {%endwith%}
                            {%endfor%}

                            <!-- More people... -->
                            </tbody>
                        </table>


                    </div>

                </div>
            </div>
            {%endfor%}
        </div>


        <div class="flex flex-col">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full bg-white sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-200">
                            <thead>
                            <tr>
                                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                    Total Order Price
                                </th>
                                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                    Total Fund Received
                                </th>
                                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                    Total Discount Given
                                </th>
                                <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left">
                                    Total Outstanding Funds
                                </th>

                            </tr>
                            </thead>
                            <tbody>

                            <tr>
                                <th class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left">
                                    {{ orders|get_value:'c_total_order_price' }}
                                </th>
                                <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                    {{ orders|get_value:'total_funds_received' }}
                                </td>
                                <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                    {{ orders|get_value:'total_discount' }}
                                </td>
                                <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                    {{ orders|get_value:'total_outstanding_funds' }}
                                </td>

                            </tr>

                            </tbody>
                        </table>
                    </div>
                    {%if orders|get_value:'error'%} <p style="font-color: red">{{ orders|get_value:'error' }}</p>
                    {%endif%}
                </div>
            </div>
        <!---    <a class="button" href="{%url 'product_app:print_report' orders|get_value:'start_date' orders|get_value:'end_date'%}" style="width: 100%;
  background-color: #10233b;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px; text-align: center;
  cursor: pointer;"
               target="_blank">print
                report</a> -->

        </div> <br> <br>

        <turbo-frame id="staff_report_loader" src="{%url 'product_app:staff_report_loader' orders|get_value:'start_date' orders|get_value:'end_date' staff.id%}">
                <h1>LOADING</h1>
            </turbo-frame>
    </turbo-frame>
</div>

{% endblock %}